name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Leptonica
      run: sudo apt-get install libleptonica-dev clang
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --lib
    - name: Check formatting
      run: cargo fmt -- --check
  windows:
    runs-on: windows-latest

    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
    - name: Install Leptonica
      run: mingw64-pkg install leptonica
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --lib
    
